# Generated by Django 3.0.3 on 2020-06-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('vip', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=20)),
                ('statut', models.CharField(max_length=20)),
                ('type_v', models.CharField(max_length=20)),
                ('groupe', models.CharField(max_length=20)),
                ('compteur', models.IntegerField()),
                ('conducteur', models.CharField(max_length=40)),
            ],
        ),
    ]
