# Generated by Django 3.0.3 on 2020-06-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0003_auto_20200614_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='vehicules_pics'),
        ),
    ]
