# Generated by Django 3.0.3 on 2020-07-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0006_auto_20200708_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='groupe',
            field=models.CharField(choices=[('C', 'Civil'), ('M', 'Militaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(choices=[('AC', 'Actif'), ('AT', 'En Atelier'), ('EP', 'En Panne'), ('HS', 'Hors Service')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type',
            field=models.CharField(choices=[('V', 'Voiture'), ('C', 'Camion'), ('M', 'Moto')], max_length=20),
        ),
    ]
