# Generated by Django 3.0.3 on 2020-07-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0007_auto_20200708_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='groupe',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Militaire', 'Militaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('En Atelier', 'En Atelier'), ('En Panne', 'En Panne'), ('Hors Service', 'Hors Service')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type',
            field=models.CharField(choices=[('Voiture', 'Voiture'), ('Camion', 'Camion'), ('Moto', 'Moto')], max_length=20),
        ),
    ]
