# Generated by Django 3.0.7 on 2020-06-18 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0004_auto_20200614_1232'),
        ('calendrier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('titre', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('observation', models.CharField(max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendrier.employees')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.Vehicule')),
            ],
        ),
    ]
