# Generated by Django 3.0.7 on 2020-07-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0002_employees_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='etat',
            field=models.CharField(default='en cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='titre',
            field=models.CharField(max_length=50),
        ),
    ]
