# Generated by Django 3.0.7 on 2020-07-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0003_auto_20200707_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='etats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='etat',
            field=models.ForeignKey(default='en cours', on_delete=django.db.models.deletion.CASCADE, to='calendrier.etats'),
        ),
    ]
