# Generated by Django 3.0.7 on 2020-07-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0004_auto_20200707_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='etat',
        ),
    ]
