# Generated by Django 3.0.7 on 2020-07-07 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0006_maintenance_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='etat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendrier.etats'),
        ),
    ]
