# Generated by Django 3.0.7 on 2020-07-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0008_remove_maintenance_etat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='etats',
            new_name='etat',
        ),
    ]
