# Generated by Django 3.0.7 on 2020-07-07 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0010_delete_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='etat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='maintenance',
            name='etat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendrier.etat'),
        ),
    ]
