# Generated by Django 3.0.7 on 2020-07-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0011_auto_20200707_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
